-   id: go-build
    name: go build check
    entry: go-build
    language: golang
    description: Runs go build, requires golang
-   id: go-test
    name: go test check
    entry: go-test
    language: golang
    description: Runs go testing, requires golang
-   id: go-imports
    name: goimports check
    entry: pre-commit-hooks/goimports/run-goimports.sh
    language: 'script'
    description: Runs goimports
-   id: errcheck
    name:  errcheck
    entry: pre-commit-hooks/errcheck/run-errcheck.sh
    language: 'script'
    description: Runs errcheck tool
-   id: dockercheck
    name:  dockercheck
    entry: pre-commit-hooks/dockercheck/run-dockercheck.sh
    language: 'script'
    description: Runs dockerfile check tool