-   id: go-build
    name: go build check
    entry: go-build
    language: golang
    description: Runs go build, requires golang
-   id: go-test
    name: go test check
    entry: go-test
    language: golang
    description: Runs go testing, requires golang
-   id: goimports
    name: goimports check
    entry: pre-commit-hooks/goimports/run-goimports.sh
    language: 'script'
    description: Runs goimports