-   id: go-build
    name: go build check
    entry: go-build
    language: golang
    description: Runs go build, requires golang
-   id: go-test
    name: go test check
    entry: go-test
    language: golang
    description: Runs go testing, requires golang